version: '3.8'

services:
  # Spring Boot application
  energy-consumption-dashboard:
    image: energy-consumption-dashboard:latest  # Image built from the Dockerfile
    container_name: energy-consumption-dashboard
    build: .
    ports:
      - "8080:8080"  # Exposing the Spring Boot app on port 8080
    environment:
      SPRING_PROFILES_ACTIVE: "docker"  # Optional: You can define custom profiles for Docker
      INFLUXDB_URL: "http://influxdb:8086"  # InfluxDB URL for connection
      INFLUXDB_DATABASE: "energy_usage"  # Default database name
    depends_on:
      - influxdb  # Ensures that InfluxDB starts before the Spring Boot app

  # InfluxDB instance to store energy data
  influxdb:
    image: influxdb:2.0  # Using InfluxDB 2.x image
    container_name: influxdb
    ports:
      - "8086:8086"  # Exposing InfluxDB's default port
    environment:
      INFLUXDB_DB: "energy_usage"  # Default database for energy usage
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "adminpassword"
      INFLUXDB_USER: "user"
      INFLUXDB_PASSWORD: "password"
    volumes:
      - influxdb_data:/var/lib/influxdb  # Persist InfluxDB data between container restarts

  # Optional: A monitoring tool like Prometheus to collect metrics
  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   depends_on:
  #     - energy-consumption-dashboard

volumes:
  influxdb_data:  # This volume will persist the data for InfluxDB

